###
GET http://localhost:8083/dictionary/test1?page=0&size=100
Accept: application/json

###
GET http://localhost:8083/dictionary/test1/PL
Accept: application/json

###
POST http://localhost:8083/dictionary/test4
Content-Type: application/json

{
  "id": "EE",
  "document": {
    "code": "EE",
    "value": [
      {
        "lang": "pl",
        "value": "POLSKA"
      },
      {
        "lang": "en",
        "value": "POLAND"
      }
    ]
  }
}

###
PUT http://localhost:8083/dictionary/test1
Content-Type: application/json

{
  "id": "PL",
  "document": {
    "code": "PL",
    "value": [
      {
        "lang": "pl",
        "value": "POL"
      },
      {
        "lang": "en",
        "value": "POLAND"
      },
      {
        "lang": "de",
        "value": "POLEN"
      }
    ]
  }
}

