com:
  pgoogol:
    searchservice:
      criteria-config:
        file: /home/pgogol/config.json

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html

spring:
  elasticsearch:
    uris: ${ELK_REST_URIS:localhost:9200}
    username: ${ELK_USERNAME:}
    password: ${ELK_PASSWORD:}
    ssl_enabled: ${ELK_SSL_ENABLED:false}

#logging:
#  file:
#    name: C:/log/log.log
#    #name: /tmp/logstash/log.log
#  pattern:
#    #console: '%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n'
#    console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [${HOSTNAME}] [%thread] %level %logger{36}@%method:%line - %msg%n'
#    #file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
#    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n'
#    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [${HOSTNAME}] [%thread] %level %logger{36}@%method:%line - %msg%n'
#  level:
#    com:
#      pgoogol:
#        search-service: ${LOG_LEVEL_ROOT:DEBUG}
server:
  port: 8083