com:
  pgoogol:
    searchservice:
      criteria-config:
        file: /home/pgogol/config.json

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html

spring:
  elasticsearch:
    uris: ${ELK_REST_URIS:localhost:9200}
    username: ${ELK_USERNAME:}
    password: ${ELK_PASSWORD:}
    ssl_enabled: ${ELK_SSL_ENABLED:false}


server:
  port: 8083